// ACTION Constants

export const BASE_URL = window.BASE_URL;

export const HEADERS = {
    'X-MG-Tenant': 'tenant-registry-ui',
    'X-MG-User': 'tenant-registry-ui'
}


//Environment Context
export const FETCH_ENVIRONMENT_CONTEXT_SUCCESS = "FETCH_ENVIRONMENT_CONTEXT_SUCCESS";
export const FETCH_ENVIRONMENT_CONTEXT_ERROR = "FETCH_ENVIRONMENT_CONTEXT_ERROR";

//Enterprise Hierarchy
export const FETCH_ENTERPRISE_HIERARCHY_PENDING = "FETCH_ENTERPRISE_HIERARCHY_PENDING";
export const FETCH_ENTERPRISE_HIERARCHY_SUCCESS = "FETCH_ENTERPRISE_HIERARCHY_SUCCESS";
export const FETCH_ENTERPRISE_HIERARCHY_ERROR = "FETCH_ENTERPRISE_HIERARCHY_ERROR";

//Query Tenants by enterprise hid
export const QUERY_TENANTS_BY_HID_PENDING = "QUERY_TENANTS_BY_HID_PENDING";
export const QUERY_TENANTS_BY_HID_SUCCESS = "QUERY_TENANTS_BY_HID_SUCCESS";
export const QUERY_TENANTS_BY_HID_ERROR = "QUERY_TENANTS_BY_HID_ERROR";

// Provision Tenant
export const PROVISION_TENANT_PENDING = "PROVISION_TENANT_PENDING";
export const PROVISION_TENANT_SUCCESS = "PROVISION_TENANT_SUCCESS";
export const PROVISION_TENANT_ERROR = "PROVISION_TENANT_ERROR";

//Provision Tenant Deployment
export const PROVISION_TENANT_DEPLOYMENT_PENDING = "PROVISION_TENANT_DEPLOYMENT_PENDING";
export const PROVISION_TENANT_DEPLOYMENT_SUCCESS = "PROVISION_TENANT_DEPLOYMENT_SUCCESS";
export const PROVISION_TENANT_DEPLOYMENT_ERROR = "PROVISION_TENANT_DEPLOYMENT_ERROR";






