--liquibase formatted sql
--changeset andries:6

CREATE INDEX HID_TO_TENANT_ID_IDX ON ACCOUNT_DEPLOY_TARGET_SCOPE (APP_ID, ENV_ID, SCOPE_ID, TENANT_HID) TABLESPACE MG_INDEX;

CREATE INDEX FK_TENANT_ALIASES_IDX ON TENANT_ALIASES (TENANT_ENTITY_ID) TABLESPACE MG_INDEX;

CREATE INDEX FK_APP_ACCOUNTS_IDX ON APP_ACCOUNT (TENANT_ID) TABLESPACE MG_INDEX;

CREATE INDEX FK_APP_ACCOUNT_DEPLOYS_IDX ON APP_ACCOUNT_DEPLOY (APP_ACCOUNT_ID) TABLESPACE MG_INDEX;

CREATE INDEX FK_ACCOUNT_DEPLOY_SCOPES_IDX ON ACCOUNT_DEPLOY_TARGET_SCOPE (APP_ACCOUNT_DEPLOY_ID) TABLESPACE MG_INDEX;