--liquibase formatted sql
--changeset andries:5

ALTER TABLE TENANT_ALIASES
    ADD CONSTRAINT FK_TENANT_ALIASES FOREIGN KEY (TENANT_ENTITY_ID) REFERENCES TENANT ON DELETE CASCADE;

ALTER TABLE APP_ACCOUNT
    ADD CONSTRAINT FK_APP_ACCOUNTS FOREIGN KEY (TENANT_ID) REFERENCES TENANT ON DELETE CASCADE;

ALTER TABLE APP_ACCOUNT_DEPLOY
    ADD CONSTRAINT FK_APP_ACCOUNT_DEPLOYS FOREIGN KEY (APP_ACCOUNT_ID) REFERENCES APP_ACCOUNT ON DELETE CASCADE;

ALTER TABLE ACCOUNT_DEPLOY_TARGET_SCOPE
    ADD CONSTRAINT FK_ACCOUNT_DEPLOY_SCOPES FOREIGN KEY (APP_ACCOUNT_DEPLOY_ID) REFERENCES APP_ACCOUNT_DEPLOY ON DELETE CASCADE;
