--liquibase formatted sql
--changeset andries:3

CREATE TABLE TENANT
(
  ACTIVE                   NUMBER(1, 0)       NOT NULL,
  CREATEBY                 VARCHAR2(255 CHAR) NOT NULL,
  CREATEDATE               TIMESTAMP          NOT NULL,
  UPDATEBY                 VARCHAR2(255 CHAR) NOT NULL,
  UPDATEDATE               TIMESTAMP          NOT NULL,
  VERSION                  NUMBER(19, 0)      NOT NULL,
  TENANT_ID                VARCHAR2(255 CHAR) NOT NULL,
  CONSTRAINT PK_TENANT PRIMARY KEY (TENANT_ID)
    USING INDEX TABLESPACE MG_INDEX
) TABLESPACE MG_DATA;

CREATE TABLE TENANT_ALIASES
(
    TENANT_ENTITY_ID         VARCHAR2(255 CHAR) NOT NULL,
    TENANT_ALIAS_ID          VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_TENANT_ALIASES PRIMARY KEY (TENANT_ENTITY_ID, TENANT_ALIAS_ID)
        USING INDEX TABLESPACE MG_INDEX
) TABLESPACE MG_DATA;

CREATE TABLE APP_ACCOUNT
(
    ACTIVE                   NUMBER(1, 0)       NOT NULL,
    CREATEBY                 VARCHAR2(255 CHAR) NOT NULL,
    CREATEDATE               TIMESTAMP          NOT NULL,
    UPDATEBY                 VARCHAR2(255 CHAR) NOT NULL,
    UPDATEDATE               TIMESTAMP          NOT NULL,
    VERSION                  NUMBER(19, 0)      NOT NULL,
    APP_ACCOUNT_ID           VARCHAR2(255 CHAR) NOT NULL,
    APP_ID                   VARCHAR2(255 CHAR) NOT NULL,
    TENANT_ID                VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_APP_ACCOUNT PRIMARY KEY (APP_ACCOUNT_ID)
        USING INDEX TABLESPACE MG_INDEX
) TABLESPACE MG_DATA;

CREATE TABLE APP_ACCOUNT_DEPLOY
(
    ACTIVE                   NUMBER(1, 0)       NOT NULL,
    CREATEBY                 VARCHAR2(255 CHAR) NOT NULL,
    CREATEDATE               TIMESTAMP          NOT NULL,
    UPDATEBY                 VARCHAR2(255 CHAR) NOT NULL,
    UPDATEDATE               TIMESTAMP          NOT NULL,
    VERSION                  NUMBER(19, 0)      NOT NULL,
    APP_ACCOUNT_DEPLOY_ID    VARCHAR2(255 CHAR) NOT NULL,
    APP_ACCOUNT_ID           VARCHAR2(255 CHAR) NOT NULL,
    ENV_ID                   VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_APP_ACCOUNT_DEPLOY PRIMARY KEY (APP_ACCOUNT_DEPLOY_ID)
        USING INDEX TABLESPACE MG_INDEX
) TABLESPACE MG_DATA;

CREATE TABLE ACCOUNT_DEPLOY_TARGET_SCOPE
(
    ACTIVE                   NUMBER(1, 0)       NOT NULL,
    CREATEBY                 VARCHAR2(255 CHAR) NOT NULL,
    CREATEDATE               TIMESTAMP          NOT NULL,
    UPDATEBY                 VARCHAR2(255 CHAR) NOT NULL,
    UPDATEDATE               TIMESTAMP          NOT NULL,
    VERSION                  NUMBER(19, 0)      NOT NULL,
    ACCOUNT_DEPLOY_SCOPE_ID  VARCHAR2(255 CHAR) NOT NULL,
    APP_ACCOUNT_DEPLOY_ID    VARCHAR2(255 CHAR) NOT NULL,
    SCOPE_ID                 VARCHAR2(255 CHAR) NOT NULL,
    TENANT_ID                VARCHAR2(255 CHAR) NOT NULL,
    ENV_ID                   VARCHAR2(255 CHAR) NOT NULL,
    APP_ID                   VARCHAR2(255 CHAR) NOT NULL,
    TENANT_HID               VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_ACCOUNT_DEPLOY_SCOPE PRIMARY KEY (ACCOUNT_DEPLOY_SCOPE_ID)
        USING INDEX TABLESPACE MG_INDEX
) TABLESPACE MG_DATA;



